In [72]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [73]:
csv_1=pd.read_csv("/home/user/Downloads/uncleaned_startup_success_failure_5000(1).csv")
csv_1.head()

,startup_id,startup_name,industry,country,founding_year,founders_count,initial_funding_usd,total_funding_usd,revenue_last_year_usd,employee_count,burn_rate_usd,market_competition,years_operated,customer_rating,reason_for_failure,status
0,S00001,Startup_1,Fintech,Canada,2011,4.0,300000.0,200000.0,28155509.0,300.0,NaN,low,6,3.0,Cash flow issues,Success
1,S00002,Startup_2,EdTech,india,2018,3.0,NaN,1000000.0,5515439.0,300.0,40000.0,low,7,1.5,Cash flow issues,Failed
2,S00003,Startup_3,AI,USA,2010,1.0,NaN,1000000.0,4256236.0,50.0,300000.0,low,8,3.0,Bad marketing,Success
3,S00004,Startup_4,Agritech,india,2018,4.0,100000.0,NaN,-100000.0,120.0,40000.0,high,15,NaN,NaN,Failed
4,S00005,Startup_5,SaaS,U.S.A,2015,5.0,50000.0,1000000.0,24374740.0,NaN,150000.0,Medium,6,3.0,NaN,Failed

In [74]:
csv_1.info()
csv_1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   startup_id             5000 non-null   object
 1   startup_name           5000 non-null   object
 2   industry               5000 non-null   object
 3   country                5000 non-null   object
 4   founding_year          5000 non-null   int64
 5   founders_count         4145 non-null   float64
 6   initial_funding_usd    4154 non-null   float64
 7   total_funding_usd      4016 non-null   float64
 8   revenue_last_year_usd  3387 non-null   float64
 9   employee_count         4360 non-null   float64
 10  burn_rate_usd          4040 non-null   float64
 11  market_competition     5000 non-null   object
 12  years_operated         5000 non-null   int64
 13  customer_rating        4156 non-null   float64
 14  reason_for_failure     4037 non-null   object
 15  status                 5000 non-null   object
dtypes: float64(7), int64(2), object(7)
memory usage: 625.1+ KB

startup_id                  0
startup_name                0
industry                    0
country                     0
founding_year               0
founders_count            855
initial_funding_usd       846
total_funding_usd         984
revenue_last_year_usd    1613
employee_count            640
burn_rate_usd             960
market_competition          0
years_operated              0
customer_rating           844
reason_for_failure        963
status                      0
dtype: int64

In [75]:
csv_1["industry"]=csv_1["industry"].str.lower()
csv_1["country"]=csv_1["country"].str.title()
csv_1["status"]=csv_1["status"].str.capitalize()
csv_1["market_competition"]=csv_1["market_competition"].str.capitalize()

In [76]:
csv_1.describe()

,founding_year,founders_count,initial_funding_usd,total_funding_usd,revenue_last_year_usd,employee_count,burn_rate_usd,years_operated,customer_rating
count,5000.000000,4145.000000,4.154000e+03,4.016000e+03,3.387000e+03,4360.000000,4040.000000,5000.000000,4156.000000
mean,2016.452400,2.993245,5.363385e+05,4.448954e+06,7.483053e+06,73.435321,144853.960396,8.151000,3.017324
std,4.052137,1.401858,5.426938e+05,4.613844e+06,9.717794e+06,100.004496,96904.189002,4.343175,1.057988
min,2010.000000,1.000000,5.000000e+04,2.000000e+05,-1.000000e+05,3.000000,40000.000000,1.000000,1.500000
25%,2013.000000,2.000000,1.000000e+05,1.000000e+06,-1.000000e+05,5.000000,90000.000000,4.000000,2.300000
50%,2016.000000,3.000000,3.000000e+05,1.000000e+06,5.349340e+05,25.000000,150000.000000,8.000000,3.000000
75%,2020.000000,4.000000,8.000000e+05,5.000000e+06,1.488899e+07,120.000000,150000.000000,12.000000,3.800000
max,2023.000000,5.000000,1.500000e+06,1.200000e+07,2.996178e+07,300.000000,300000.000000,15.000000,4.500000

In [77]:
num_cols = csv_1.select_dtypes(include=np.number).columns
for col in num_cols:
    csv_1[col].fillna(csv_1[col].median(), inplace=True)

/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)
/tmp/ipykernel_9221/1495785633.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna(csv_1[col].median(), inplace=True)

In [78]:
num_cols = csv_1.select_dtypes(include='object').columns
for col in num_cols:
    csv_1[col].fillna("Unknown", inplace=True)

/tmp/ipykernel_9221/363069139.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csv_1[col].fillna("Unknown", inplace=True)

In [79]:
csv_1.isnull().sum()

startup_id               0
startup_name             0
industry                 0
country                  0
founding_year            0
founders_count           0
initial_funding_usd      0
total_funding_usd        0
revenue_last_year_usd    0
employee_count           0
burn_rate_usd            0
market_competition       0
years_operated           0
customer_rating          0
reason_for_failure       0
status                   0
dtype: int64

In [80]:
csv_1

,startup_id,startup_name,industry,country,founding_year,founders_count,initial_funding_usd,total_funding_usd,revenue_last_year_usd,employee_count,burn_rate_usd,market_competition,years_operated,customer_rating,reason_for_failure,status
0,S00001,Startup_1,fintech,Canada,2011,4.0,300000.0,200000.0,28155509.0,300.0,150000.0,Low,6,3.0,Cash flow issues,Success
1,S00002,Startup_2,edtech,India,2018,3.0,300000.0,1000000.0,5515439.0,300.0,40000.0,Low,7,1.5,Cash flow issues,Failed
2,S00003,Startup_3,ai,Usa,2010,1.0,300000.0,1000000.0,4256236.0,50.0,300000.0,Low,8,3.0,Bad marketing,Success
3,S00004,Startup_4,agritech,India,2018,4.0,100000.0,1000000.0,-100000.0,120.0,40000.0,High,15,3.0,Unknown,Failed
4,S00005,Startup_5,saas,U.S.A,2015,5.0,50000.0,1000000.0,24374740.0,25.0,150000.0,Medium,6,3.0,Unknown,Failed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S04996,Startup_4996,energy,Germany,2018,4.0,100000.0,1000000.0,29564130.0,50.0,150000.0,High,6,2.3,Unknown,Failed
4996,S04997,Startup_4997,ecommerce,Usa,2018,2.0,300000.0,1000000.0,534934.0,50.0,300000.0,High,12,2.3,Unknown,Failed
4997,S04998,Startup_4998,foodtech,Uk,2016,4.0,100000.0,200000.0,19129201.0,3.0,90000.0,Medium,2,2.3,Founder conflict,Success
4998,S04999,Startup_4999,ai,Usa,2011,3.0,50000.0,5000000.0,11212802.0,300.0,300000.0,High,6,3.0,Lack of market demand,Success
4999,S05000,Startup_5000,health tech,India,2010,2.0,100000.0,12000000.0,534934.0,50.0,90000.0,Low,13,4.5,Cash flow issues,Failed

In [81]:
csv_1.loc[csv_1["revenue_last_year_usd"]<0,"revenue_last_year_usd"]=0

In [82]:
median_value=csv_1["revenue_last_year_usd"].median()
csv_1.loc[csv_1["revenue_last_year_usd"]<0,"revenue_last_year_usd"]=median_value

In [83]:
(csv_1["revenue_last_year_usd"]<0).sum()

np.int64(0)

In [84]:
Q1=csv_1["revenue_last_year_usd"].quantile(0.25)
Q3=csv_1["revenue_last_year_usd"].quantile(0.75)
IOR=Q1-Q3

In [85]:
lower_bound=Q1-1.5*IOR
upper_bound=Q3+1.5*IOR

In [86]:
csv_1["revenue_last_year_usd"]=csv_1["revenue_last_year_usd"].clip(lower_bound,upper_bound)

In [87]:
csv_1.shape

(5000, 16)

In [88]:
csv_1["status"]=csv_1["status"].map({"Success":1,"Failed":0})

In [89]:
csv_1 = pd.get_dummies(csv_1, columns=['industry','country','market_competition'], drop_first=True)

In [90]:
csv_1['profit_ratio'] = csv_1['revenue_last_year_usd'] / csv_1['total_funding_usd']
csv_1['funding_per_employee'] = csv_1['total_funding_usd'] / csv_1['employee_count']

In [91]:
X = csv_1.drop(['startup_id','startup_name','reason_for_failure','status'], axis=1)
y = csv_1['status']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape

((4000, 33), (1000, 33))

In [92]:
csv_1.dtypes

startup_id                    object
startup_name                  object
founding_year                  int64
founders_count               float64
initial_funding_usd          float64
total_funding_usd            float64
revenue_last_year_usd        float64
employee_count               float64
burn_rate_usd                float64
years_operated                 int64
customer_rating              float64
reason_for_failure            object
status                         int64
industry_ai                     bool
industry_e commerce             bool
industry_ecommerce              bool
industry_ed-tech                bool
industry_edtech                 bool
industry_energy                 bool
industry_fintech                bool
industry_foodtech               bool
industry_health tech            bool
industry_healthtech             bool
industry_realestate             bool
industry_saas                   bool
industry_transport              bool
industry_travel                 bool
country_Canada                  bool
country_Germany                 bool
country_India                   bool
country_U.S.A                   bool
country_Uk                      bool
country_Usa                     bool
market_competition_Low          bool
market_competition_Medium       bool
profit_ratio                 float64
funding_per_employee         float64
dtype: object

In [93]:
csv_1=csv_1.drop(['startup_id','startup_name'],axis=1)

In [94]:
csv_1= csv_1.drop(['reason_for_failure'], axis=1)

In [95]:
csv_1 = csv_1.drop(['industry_e commerce','industry_ed-tech','industry_health tech','country_Usa'], axis=1)

In [96]:
bool_cols = csv_1.select_dtypes(include='bool').columns
csv_1[bool_cols] = csv_1[bool_cols].astype(int)

In [97]:
bool_cols = csv_1.select_dtypes(include='bool').columns
csv_1[bool_cols] = csv_1[bool_cols].astype(int)

In [98]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [99]:
csv_1 = csv_1.drop(['profit_ratio','funding_per_employee'], axis=1)

In [100]:
csv_1['funding_efficiency'] = csv_1['revenue_last_year_usd'] / csv_1['total_funding_usd']
csv_1['burn_efficiency'] = csv_1['revenue_last_year_usd'] / csv_1['burn_rate_usd']

In [101]:
csv_1['status'].value_counts()

status
0    3302
1    1698
Name: count, dtype: int64

In [ ]:
csv_1.to_csv("cleaned_startup(4).csv")

In [103]:
csv_1

,founding_year,founders_count,initial_funding_usd,total_funding_usd,revenue_last_year_usd,employee_count,burn_rate_usd,years_operated,customer_rating,status,...,industry_travel,country_Canada,country_Germany,country_India,country_U.S.A,country_Uk,market_competition_Low,market_competition_Medium,funding_efficiency,burn_efficiency
0,2011,4.0,300000.0,200000.0,1.160397e+07,300.0,150000.0,6,3.0,1,...,0,1,0,0,0,0,1,0,58.019841,77.359787
1,2018,3.0,300000.0,1000000.0,5.515439e+06,300.0,40000.0,7,1.5,0,...,0,0,0,1,0,0,1,0,5.515439,137.885975
2,2010,1.0,300000.0,1000000.0,4.256236e+06,50.0,300000.0,8,3.0,1,...,0,0,0,0,0,0,1,0,4.256236,14.187453
3,2018,4.0,100000.0,1000000.0,0.000000e+00,120.0,40000.0,15,3.0,0,...,0,0,0,1,0,0,0,0,0.000000,0.000000
4,2015,5.0,50000.0,1000000.0,1.160397e+07,25.0,150000.0,6,3.0,0,...,0,0,0,0,1,0,0,1,11.603968,77.359787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2018,4.0,100000.0,1000000.0,1.160397e+07,50.0,150000.0,6,2.3,0,...,0,0,1,0,0,0,0,0,11.603968,77.359787
4996,2018,2.0,300000.0,1000000.0,5.349340e+05,50.0,300000.0,12,2.3,0,...,0,0,0,0,0,0,0,0,0.534934,1.783113
4997,2016,4.0,100000.0,200000.0,1.160397e+07,3.0,90000.0,2,2.3,1,...,0,0,0,0,0,1,0,1,58.019841,128.932979
4998,2011,3.0,50000.0,5000000.0,1.121280e+07,300.0,300000.0,6,3.0,1,...,0,0,0,0,0,0,0,0,2.242560,37.376007
4999,2010,2.0,100000.0,12000000.0,5.349340e+05,50.0,90000.0,13,4.5,0,...,0,0,0,1,0,0,1,0,0.044578,5.943711